#高可用注册中心节点2
server:
  port: 8002

eureka:
  instance:
    hostname: peer2
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8001/eureka/,http://peer3:8003/eureka/

spring:
  application:
    name: kevin-peer2