server:
  port: 8030
spring:
  application:
    name: kevin-log-sleuth
  zipkin:
    base-url: http://127.0.0.1:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/